apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: crew-ai-test25102109
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/crew-ai-test25102109:1c54f71483c8706e81661b978aa6008058017a98@sha256:92fdbdee9615a3e4e567422a558d61ebca2a2ac2ab88ba5a6c09803bcc4ae2d7 # use pre-built to bootstrap
          name: app-inference
